Revert "Delete package_index files from the .arduino15 folder after each verification"
This reverts commit 5e64529f55a7d468976c4afbe96513bccd8f734a.

I need to revert this commit because it causes verification for Arduino
official boards othe than Arduino AVR Boards to fail:

Error: sam: Unknown architecture

I believe this is because the missing package_index.json file is
replaced by the version bundled with the IDE, which only contains
Arduino AVR Boards. I have found a solution that solves the
1.6.5+1.6.5-r5 bug as well as the bug that the original fix caused.